name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Default Features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --all-features

  test_matrix:
    name: Test Feature Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: [rusteron, aeron-rs]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --no-default-features --features ${{ matrix.feature }}
      - name: Run tests
        run: cargo test --verbose --no-default-features --features ${{ matrix.feature }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clippy
        run: cargo clippy -- -D warnings

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        run: cargo fmt -- --check
